name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up OCaml
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: 5.1.1

    - name: Install dependencies
      run: |
        eval $(opam env)
        opam update -y
        opam depext -y --with-test . || true
        opam install . --deps-only --with-test -y
        # Ensure TLS backends are present (some distros miss these via transitive deps)
        opam install -y tls-lwt

    - name: Build
      run: |
        eval $(opam env)
        dune build -p opencage

    - name: Run tests
      run: |
        eval $(opam env)
        dune runtest -j1 --no-buffer
